name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup MUSL
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools
      - name: Build for x86_64-unknown-linux-musl
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl
          zip -j sanjo_x86_64-unknown-linux-musl.zip target/x86_64-unknown-linux-musl/release/sanjo
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
